import pathlib,json,hashlib,datetime
D=pathlib.Path(__file__).parent;R=pathlib.Path('/private/tmp/sberindex-official-laws-20261007');j=json.loads((D/'RESULT.json').read_text());H=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();links={}
for rel in ['shock-radar/runs/National_equal_information_20261006','economic-atlas/runs/Consumer_closeout_20261006','economic-atlas/runs/Consumer_mechanisms_20261007']:
 m=json.loads((R/rel/'manifest.json').read_text());f=m.get('files',{});links[rel]={}
 for n in ['predictions.parquet','metrics.json','protocol.json']:
  expected=f.get(n)
  if isinstance(expected,dict):expected=expected.get('sha256',expected.get('SHA'))
  if expected:assert H(R/rel/n)==expected
  links[rel][n]={'actual_SHA':H(R/rel/n),'manifest_expected_SHA':expected,'verified':expected is not None}
report={'state':'SAVED_NUMERIC_CLAIMS_VERIFIED_NOT_SCIENTIFIC_PASS','checked_at_UTC':j['checked_at_UTC'],'how':'One bounded Arrow row-batch read, independent stdlib abs/math.fsum arithmetic; no author metrics function imported; full table unique keys/calendar/finite predictions and paired supported masks verified; CI readback only','national':{'scope':'20IDs ×6categories ×6targets =120series/720paired rows,H12,Jul-Dec2024 already viewed','prediction_SHA':j['input_pins']['shock-radar/runs/National_equal_information_20261006/predictions.parquet']['SHA'],'full_key_SHA':j['national']['full_key_SHA'],'mae':j['national']['pooled_mae'],'improvement_percent':j['national']['gain_percent'],'marketplaces_loss_percent':j['national']['marketplace_loss_percent'],'winning_model':'national_yoy_lag1 simple model, not national_prophet regressor','vintage':'Frozen2026-10-05 national data; historic asof unknown; no new holdout'},'consumer':j['consumer_claim_checks'],'full_consumer_coverage':[{'table':n,**{k:v for k,v in s.items()if k!='results'}}for n,s in j['consumer_full_table_coverage'].items()],'manifest_links':links,'findings':['Requested rounded numerical statements agree with saved paired rows.','Do not label598.09 as Prophet with a national regressor: that regressor model scored946.14; the winner is simple national_yoy_lag1.','2.69%/3.79% describe total correction relative ProfileSES, not neighbours alone.','Both saved incremental-peer intervals includezero; no new CI or significance test performed.','The720row pilot and integration viewed2024 do not establish independent scientificPASS, historical available_at, causal effect, fullChronos comparison or early warning.','D01 and other submission sentences outside this specified scope were not independently recalculated in this operation.'],'submission_readiness':'Numerical wording can support a qualified retrospective submission; no numerical blocker found in requested claims. Owner must submit with actual identity/contact/consents and jury code/input access; this audit does not prove those or all scientific tasks complete.','elapsed_seconds_including_freeze_schema_setup':j['elapsed_from_original_anchor'],'sampled_peak_RSS_bytes':j['sampled_peak_RSS_bytes'],'limits':{'time300':True,'RSS1GiB_sampled':True,'output128MiB':True,'CPU_env1':True,'continuous_resource_PASS':False},'syntax_correction':'An initial syntax-only else-spacing error prevented any code execution; invalid code and log preserved, corrected code frozen before one actual arithmetic scan, original anchor unchanged.','scientific_pass':False,'models_fits_bootstraps_newwindows':0}
(D/'REPORT.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');(D/'MANIFEST.json').write_text(json.dumps({p.name:{'SHA':H(p),'bytes':p.stat().st_size}for p in D.iterdir()if p.is_file()and p.name!='MANIFEST.json'},indent=2)+'\n');print('REPORT_SHA',H(D/'REPORT.json'));print('RESULT_SHA',H(D/'RESULT.json'));print('MANIFEST_SHA',H(D/'MANIFEST.json'))
